linters-settings:
  govet:
    check-shadowing: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - mocks
    - bin
